apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-binding
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountName
    secretKeyRef:
      name: storage:accountName
  - name: accountKey
    secretKeyRef:
      name: storage:accountKey
  - name: queueName
    value: "order"
  - name: pollingInterval
    value: "10"
  - name: ttlInSeconds
    value: "120"
  - name: decodeBase64
    value: "false"
  - name: encodeBase64
    value: "false"
  - name: visibilityTimeout
    value: "30s"
  - name: route
    value: "/order-binding/checkout"
  - name: direction
    value: "input, output"
auth:
  secretStore: my-local-secret-store