apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-subscription
spec:
  topic: orders
  routes:
    default: /orders-pub-sub/checkout
  pubsubname: my-pub-sub
scopes: # Access only by apps with IDs
- webapi