apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-state-store
spec:
  type: state.in-memory
  version: v1
  metadata:
  - name: actorStateStore
    value: "true"

# --- Redis ---
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: my-state-store
# spec:
#   type: state.redis
#   version: v1
#   metadata:
#   - name: redisHost
#     value: 127.0.0.1:6379