@HostAddress = https://localhost:7007

GET {{HostAddress}}/state
Accept: application/json

### State -> Save

POST {{HostAddress}}/state
Content-type: application/json

{
  "Name": "John Doe",
  "Age": 10
}

### State -> Delete

DELETE {{HostAddress}}/state

### State -> Get with ETag

GET {{HostAddress}}/state/with-etag
Accept: application/json

### State -> Save with ETag

POST {{HostAddress}}/state/with-etag
Content-type: application/json

{
  "eTag": "1",
  "state": {
    "name": "John Doe",
    "age": 15
  }
}

### Invoke Method

GET {{HostAddress}}/invoke-method
Accept: application/json

### GetState via Dapr
GET http://localhost:3510/v1.0/state/MyStateStore/test-key
Accept: application/json

### Invoke via Dapr
GET http://localhost:3510/v1.0/invoke/echo-server/method/my-endpoint-name?key=value
Accept: application/json